### ISSUE TITLE
Create Index Page

### ISSUE THREAD

**Issue by SilvanBaach** [GenZHAW/GNX_Webapp#29]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Create an index Site like in the sketch. Please refer to the brandbook and use the defined colors and fonts (Orbitron and Montserrat).

Logo: Use /res/logo/logo_webheader_white.png
Background: Use /res/background/background_1.jpg
Team Icons: You find all of them in /res/teams

No Links or buttons should work at this point.

Create an express route for "/"

**Describe alternatives you've considered**
None

**Additional context**
Sketch:
![index](https://user-images.githubusercontent.com/31915264/229099676-0af3b43c-2b59-4f8c-883e-55fa604a3633.png)

**Comment by SilvanBaach** [comment]
@Alperen1999 @jondef

**Comment by ArmandoShala** [comment]
Could you provide me the needed team names?

**Comment by ArmandoShala** [comment]
Nvm found them
