### ISSUE TITLE
Create Readme

### ISSUE THREAD

**Issue by ArmandoShala** [GenZHAW/GNX_Webapp#3]
The README file should be created as it provides essential information about a project, such as installation instructions, usage guidelines, and troubleshooting tips. It helps users and collaborators understand the project and get started quickly, saving time and reducing confusion.

**Comment by BadrOutiti** [comment]
@ArmandoShala I opened a PR, please check it out!

**Comment by ArmandoShala** [comment]
Unfortunately I cannot find a PR. Could you help me with finding it?

**Comment by BadrOutiti** [comment]
> Unfortunately I cannot find a PR. Could you help me with finding it?

You already merged it: https://github.com/GenZHAW/GNX_Webapp/pull/36

**Comment by ArmandoShala** [comment]
Ahh, okay. Thanks for clarification
