### ISSUE TITLE
Ressources can not be loaded

### ISSUE THREAD

**Issue by BadrOutiti** [GenZHAW/GNX_Webapp#43]
**Describe the bug**
When linking to the css stylesheets, the website can not load them

**To Reproduce**
1. Link the css sheat
2. Open the site in the browser

**Expected behavior**
Showing the correct stylesheet

**Screenshots**
![image](https://user-images.githubusercontent.com/79651672/232869011-252a5f36-7b66-443a-9fac-064a7466dc12.png)

**Comment by SilvanBaach** [comment]
Works fine now!
