### ISSUE TITLE
Create needed Styles

### ISSUE THREAD

**Issue by ArmandoShala** [GenZHAW/GNX_Webapp#46]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Have a styles.css (and other) components to add it in all HTMLs to everything is styled like Shindy

**Describe alternatives you've considered**
An alternative would be, to define each styled individually in each file, but that's nonsense. So its my way or highway

**Additional context**
None

**Comment by SilvanBaach** [comment]
Please clean up the styles
