### ISSUE TITLE
Login enhancements

### ISSUE THREAD

**Issue by SilvanBaach** [GenZHAW/GNX_Webapp#60]
**Is your feature request related to a problem? Please describe.**
Basic login works. We need a few more features

**Describe the solution you'd like**
- If a User types in the password 5 times wrong the user should get blocked
- A User should be able to reset its password via E-Mail

**Describe alternatives you've considered**
-

**Additional context**
-

**Comment by ArmandoShala** [comment]
Todo: Ask @SilvanBaach for email server and login credentials
